services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped